const themes = [
  {
    id: "minimal-corporate",
    name: "Minimal Corporate Grid",
    direction: "ltr",
    layoutVariant: "grid",
    tokens: {
      accentColor: "#1f2937",
      backgroundColor: "#ffffff",
      textColor: "#111111",
      mutedColor: "#6b7280",
      borderColor: "#e5e7eb",
      tableHeaderBg: "#f9fafb",
      borderRadius: 10,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 700,
      titleFontSize: 32,
      labelFontSize: 10,
      bodyFontSize: 12,
      uppercaseLabels: true,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "md",
      zebraRows: false,
      zebraColor: "#f9fafb",
      spacing: "normal",
      headerLayout: "split",
      showLogo: true,
      logoSize: "md",
    },
  },
  {
    id: "fast-invoice",
    name: "Fast Invoice",
    direction: "ltr",
    layoutVariant: "fast",
    tokens: {
      accentColor: "#111111",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      mutedColor: "#555555",
      borderColor: "#e5e7eb",
      tableHeaderBg: "#ffffff",
      borderRadius: 0,
      borderStyle: "none",
      fontFamily: "inter",
      headingWeight: 700,
      titleFontSize: 22,
      labelFontSize: 10,
      bodyFontSize: 12,
      uppercaseLabels: false,
      tableStyle: "lines",
      showColumnBorders: false,
      rowSeparator: "none",
      cellPadding: "sm",
      zebraRows: false,
      zebraColor: "#ffffff",
      spacing: "compact",
      headerLayout: "split",
      showLogo: false,
      logoSize: "sm",
    },
  },
  {
    id: "bold-stripe",
    name: "Bold Modern Stripe",
    direction: "ltr",
    layoutVariant: "stripe",
    tokens: {
      accentColor: "#2563eb",
      backgroundColor: "#ffffff",
      textColor: "#0b0f19",
      mutedColor: "#64748b",
      borderColor: "#cbd5e1",
      tableHeaderBg: "#f8fafc",
      borderRadius: 14,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 800,
      titleFontSize: 36,
      labelFontSize: 10,
      bodyFontSize: 12,
      uppercaseLabels: true,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "md",
      zebraRows: false,
      zebraColor: "#f8fafc",
      spacing: "normal",
      headerLayout: "split",
      showLogo: true,
      logoSize: "md",
    },
  },
  {
    id: "startup-cards",
    name: "Startup Friendly Cards",
    direction: "ltr",
    layoutVariant: "cards",
    tokens: {
      accentColor: "#0ea5e9",
      backgroundColor: "#ffffff",
      textColor: "#0b1220",
      mutedColor: "#475569",
      borderColor: "#bae6fd",
      tableHeaderBg: "#f0f9ff",
      borderRadius: 18,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 700,
      titleFontSize: 30,
      labelFontSize: 10,
      bodyFontSize: 12,
      uppercaseLabels: false,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "md",
      zebraRows: true,
      zebraColor: "#f0f9ff",
      spacing: "normal",
      headerLayout: "split",
      showLogo: true,
      logoSize: "md",
    },
  },
  {
    id: "luxury-elegant",
    name: "Luxury Elegant",
    direction: "ltr",
    layoutVariant: "luxury",
    tokens: {
      accentColor: "#8a6d3b",
      backgroundColor: "#ffffff",
      textColor: "#111111",
      mutedColor: "#6b5e55",
      borderColor: "#e7e2da",
      tableHeaderBg: "#ffffff",
      borderRadius: 0,
      borderStyle: "none",
      fontFamily: "serif",
      headingWeight: 700,
      titleFontSize: 40,
      labelFontSize: 10,
      bodyFontSize: 12,
      uppercaseLabels: true,
      tableStyle: "lines",
      showColumnBorders: false,
      rowSeparator: "none",
      cellPadding: "md",
      zebraRows: false,
      zebraColor: "#ffffff",
      spacing: "spacious",
      headerLayout: "center",
      showLogo: true,
      logoSize: "md",
    },
  },
  {
    id: "bw-ledger",
    name: "B/W Ledger",
    direction: "ltr",
    layoutVariant: "ledger",
    tokens: {
      accentColor: "#000000",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      mutedColor: "#444444",
      borderColor: "#000000",
      tableHeaderBg: "#f5f5f5",
      borderRadius: 0,
      borderStyle: "thin",
      fontFamily: "mono",
      headingWeight: 800,
      titleFontSize: 24,
      labelFontSize: 10,
      bodyFontSize: 11,
      uppercaseLabels: true,
      tableStyle: "boxed",
      showColumnBorders: true,
      rowSeparator: "thin",
      cellPadding: "sm",
      zebraRows: false,
      zebraColor: "#f5f5f5",
      spacing: "compact",
      headerLayout: "split",
      showLogo: false,
      logoSize: "sm",
    },
  },
  {
    id: "arabic-diwan",
    name: "Arabic Diwan (RTL)",
    direction: "rtl",
    layoutVariant: "arabic-diwan",
    tokens: {
      accentColor: "#0f766e",
      backgroundColor: "#ffffff",
      textColor: "#111111",
      mutedColor: "#475569",
      borderColor: "#d1d5db",
      tableHeaderBg: "#f8fafc",
      borderRadius: 12,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 800,
      titleFontSize: 34,
      labelFontSize: 11,
      bodyFontSize: 13,
      uppercaseLabels: false,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "md",
      zebraRows: false,
      zebraColor: "#f8fafc",
      spacing: "normal",
      headerLayout: "split",
      showLogo: true,
      logoSize: "md",
    },
  },
  {
    id: "arabic-modern",
    name: "Arabic Modern Tech (RTL)",
    direction: "rtl",
    layoutVariant: "arabic-modern",
    tokens: {
      accentColor: "#1d4ed8",
      backgroundColor: "#ffffff",
      textColor: "#0b1220",
      mutedColor: "#64748b",
      borderColor: "#e2e8f0",
      tableHeaderBg: "#f1f5f9",
      borderRadius: 14,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 800,
      titleFontSize: 32,
      labelFontSize: 11,
      bodyFontSize: 12,
      uppercaseLabels: false,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "md",
      zebraRows: true,
      zebraColor: "#f1f5f9",
      spacing: "normal",
      headerLayout: "right",
      showLogo: true,
      logoSize: "sm",
    },
  },
  {
    id: "blueprint",
    name: "Blueprint Technical",
    direction: "ltr",
    layoutVariant: "blueprint",
    tokens: {
      accentColor: "#0f172a",
      backgroundColor: "#ffffff",
      textColor: "#0b1220",
      mutedColor: "#334155",
      borderColor: "#cbd5e1",
      tableHeaderBg: "#f8fafc",
      borderRadius: 0,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 800,
      titleFontSize: 28,
      labelFontSize: 9,
      bodyFontSize: 11,
      uppercaseLabels: true,
      tableStyle: "boxed",
      showColumnBorders: true,
      rowSeparator: "thin",
      cellPadding: "sm",
      zebraRows: false,
      zebraColor: "#f8fafc",
      spacing: "normal",
      headerLayout: "split",
      showLogo: false,
      logoSize: "sm",
    },
  },
  {
    id: "retail-compact",
    name: "Retail Compact",
    direction: "ltr",
    layoutVariant: "compact",
    tokens: {
      accentColor: "#111111",
      backgroundColor: "#ffffff",
      textColor: "#111111",
      mutedColor: "#4b5563",
      borderColor: "#e5e7eb",
      tableHeaderBg: "#f3f4f6",
      borderRadius: 8,
      borderStyle: "thin",
      fontFamily: "inter",
      headingWeight: 800,
      titleFontSize: 20,
      labelFontSize: 9,
      bodyFontSize: 10,
      uppercaseLabels: true,
      tableStyle: "boxed",
      showColumnBorders: false,
      rowSeparator: "thin",
      cellPadding: "sm",
      zebraRows: false,
      zebraColor: "#f3f4f6",
      spacing: "compact",
      headerLayout: "split",
      showLogo: false,
      logoSize: "sm",
    },
  },
];

function getThemeById(id) {
  const match = themes.find((t) => t.id === id);
  return match ?? themes[0];
}

module.exports = { themes, getThemeById };

